public class Main {
    public static void main(String[] args){
        // Check Book Availability Here At Model Level...
        // Exception Name Should be Improved...
        // Pay fine should be on Main Function...
        // Use Singleton...
        // Use Enum...
        // IMPROVEMENT CODE STYLE...
        // Think Once More for Modelling...
        // Keep Type Enum...
        // Check for Books Limit and during Availability...
    }
}
